improve API for getting performance counters
furiosa-ai/device-api pull request #81
Opened 2023-06-30 07:23 UTC by libc-furiosa

Update API for getting performance counters for better precision and add python binding.
It's still not a perfect implementation, but it works better than the last version.
It's still experimental, so I'll continue to make improvements.

2023-07-03 02:02 UTC, yw-furiosa commented on bindings/python/src/device.rs
> +    pub fn performance_counters(&self) -> Vec<(DeviceFilePy, PerformanceCounterPy)> {
함수 설명 주석이 빠진 것 같습니다

2023-07-03 02:05 UTC, yw-furiosa commented on device-api/src/perf_regs.rs
> +        };
std::cmp 를 사용하면 코드가 좀 더 깔끔해질 것 같습니다.

```suggestion
        let task_cycle_gap = std::cmp::min(cycle_gap, task_cycle_gap);

        let tensor_cycle_gap = std::cmp::min(task_cycle_gap, tensor_cycle_gap);
```

2023-07-03 02:06 UTC, yw-furiosa commented on device-api/src/perf_regs.rs
> +            },
여기도 std::cmp를 쓰면 좋을 것 같습니다.
```suggestion
            task_execution_cycle: std::cmp::min(task_cycle_gap, u32::MAX as usize) as u32,
```

2023-07-03 02:12 UTC, yw-furiosa requested changes
사소한 코맨트 몇개 남겼습니다. 한가지 추가가 필요한 부분은 새로 추가해주신 `Utilization`가 `PerformanceCounter`가 python module에 포함되지 않아서 사용자에게 노출되지 못하고 있습니다. bindings/python/lib.rs 에서 모듈에 추가해주어야 합니다. #80 에서 추가하신 `ClockFrequency`에도 같은 문제가 발생합니다. 제가 리뷰를 좀 더 꼼꼼히 봤어야 하는데 죄송합니다. 이 부분만 추가해주시면 될 것 같습니다. 수고하셨습니다!

2023-07-03 02:15 UTC, libc-furiosa commented
@yw-furiosa 앗 그렇네요. 확인 감사드립니다.
이 PR에서 마저 수정해서 올리겠습니다.

빌드된 whl을 다른 환경에서 설치해서 테스트했을 때는 잘 됐었는데 이게 오히려 왜 되었는질 모르겠네요.

2023-07-03 06:08 UTC, yw-furiosa approved these changes
수고하셨습니다!

2023-07-10 05:25 UTC, hyunsik approved these changes
저도 좋은 것 같습니다. 수고 많으셨습니다!

2023-07-10 06:35 UTC, merged