Change python package name
furiosa-ai/device-api pull request #92
Opened 2023-07-18 02:49 UTC by yw-furiosa

Change python package name from "furiosa_device" to "furiosa_native_device".

2023-07-19 17:03 UTC, hyunsik approved these changes
수고하셨습니다. 저는 좋은 것 같습니다. @libc-furiosa 님 머지해도 될까요?

2023-07-20 05:32 UTC, ileixe commented
@yw-furiosa 님 저희 python packager가 `-`을 쓰고 있어서요, 여기서도 통일하면 어떨까요?

```
(.venv) furiosa-litmus$ pip list | grep furiosa
furiosa-cli                              0.10.0.dev230718
furiosa-common                           0.10.0.dev230718
furiosa_device                           0.2.1.dev0
furiosa-litmus                           0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-litmus
furiosa-models                           0.9.0.dev0       /home/ys/Source/Furiosa/sdk/furiosa-models
furiosa-native-postprocess               0.9.0
furiosa-native-runtime                   0.10.0.dev230719
furiosa-optimizer                        0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-optimizer
furiosa-quantizer                        0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-quantizer
furiosa-quantizer-impl                   0.10.0
furiosa-runtime                          0.10.0.dev0
furiosa-sdk                              0.10.0.dev0
furiosa-server                           0.10.0.dev0
furiosa-serving                          0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-serving
furiosa-tools                            0.10.0.dev230718
```

2023-07-20 05:34 UTC, ileixe requested changes
@yw-furiosa 님 저희 python packager가 `-`을 쓰고 있어서요, 여기서도 통일하면 어떨까요?

```
(.venv) furiosa-litmus$ pip list | grep furiosa
furiosa-cli                              0.10.0.dev230718
furiosa-common                           0.10.0.dev230718
furiosa_device                           0.2.1.dev0
furiosa-litmus                           0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-litmus
furiosa-models                           0.9.0.dev0       /home/ys/Source/Furiosa/sdk/furiosa-models
furiosa-native-postprocess               0.9.0
furiosa-native-runtime                   0.10.0.dev230719
furiosa-optimizer                        0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-optimizer
furiosa-quantizer                        0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-quantizer
furiosa-quantizer-impl                   0.10.0
furiosa-runtime                          0.10.0.dev0
furiosa-sdk                              0.10.0.dev0
furiosa-server                           0.10.0.dev0
furiosa-serving                          0.10.0.dev0      /home/ys/Source/Furiosa/sdk/furiosa-sdk/python/furiosa-serving
furiosa-tools                            0.10.0.dev230718
```

2023-07-20 05:41 UTC, yw-furiosa commented
네 package 이름도 이 pr에서 furiosa-native-device로 '-'를 쓰도록 수정했는데 위 글을 잘못 적었네요. [pyproject](https://github.com/furiosa-ai/device-api/blob/f12c9e6ca8deb1205601700b826834326378afd3/bindings/python/pyproject.toml#L6)에 반영되어 있습니다.
```
$ pip list | grep furiosa     
furiosa-native-device 0.2.1.dev0
```

2023-07-20 05:49 UTC, ileixe approved these changes

2023-07-20 06:12 UTC, merged